# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: 
    - main
    - master
  pull_request:
    branches: 
    - main
    - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
  packages: write
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker-frontend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Prepare Docker tag
        id: vars
        run: |
          TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "tag=$TAG" >> $GITHUB_OUTPUT
      - name: Login to GitLab Registry
        uses: docker/login-action@v3.6.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image with build args
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./docker/frontend/Dockerfile
            push: true
            tags: ghcr.io/agdsn/identman-frontend:latest
            build-args: |
              - REACT_APP_API=http://10.130.72.107:8000
  docker-backend:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      - name: Login to GitLab Registry
        uses: docker/login-action@v3.6.0
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image with build args
        uses: docker/build-push-action@v6
        with:
            context: .
            file: ./docker/fastapi/Dockerfile
            push: true
            tags: ghcr.io/agdsn/identman-backend:latest
